name: Renew Certificates
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  TF_IN_AUTOMATION: true
  STACK: infrastructure/acme
  PORKBUN_API_KEY: ${{ secrets.PORKBUN_API_KEY }}
  PORKBUN_SECRET_API_KEY: ${{ secrets.PORKBUN_SECRET_API_KEY }}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  terraform-apply:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Authenticate Terraform Providers
        uses: ./actions/terraform-provider-auth
        with:
          step: apply
          stack: ${{ env.STACK }}

      - name: Terraform Init
        uses: seanchristians/lab/actions/terraform-init@main
        with:
          working-directory: ${{ env.STACK }}

      - name: Terraform Plan
        id: plan
        run: |
          PLAN_EXIT_CODE=0
          terraform -chdir="$STACK" plan -input=false -no-color -compact-warnings -detailed-exitcode -out=tfplan || PLAN_EXIT_CODE=$?
          if [ $PLAN_EXIT_CODE -eq 2 ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          elif [ $PLAN_EXIT_CODE -eq 0 ]; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            exit $PLAN_EXIT_CODE
          fi

      - name: Terraform Apply
        if: steps.plan.outputs.changes == 'true'
        run: |
          terraform -chdir="$STACK" apply -input=false -auto-approve tfplan
