name: Renew Certificates
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  TF_IN_AUTOMATION: true
  STACK: infrastructure/acme

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  terraform-apply:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ${{ env.STACK }}
    steps:
      - uses: seanchristians/lab/actions/terraform@main
        with:
          tf-backend-aws-bucket: ${{ vars.TF_BACKEND_AWS_BUCKET }}
          tf-backend-aws-region: ${{ vars.TF_BACKEND_AWS_REGION }}
          tf-backend-aws-role: ${{ vars.TF_BACKEND_AWS_ROLE }}
          stack: ${{ env.STACK }}

      - name: Terraform Plan
        id: plan
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: |
          PLAN_EXIT_CODE=0
          terraform plan -input=false -no-color -compact-warnings -detailed-exitcode -out=tfplan || PLAN_EXIT_CODE=$?
          echo "plan=$PLAN_EXIT_CODE" >> $GITHUB_OUTPUT

      - name: Terraform Apply
        if: steps.plan.outputs.plan == 2
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: |
          terraform apply -input=false -auto-approve tfplan
