name: Terraform Network Stack (development)
on:
  workflow_dispatch:
  pull_request:
    paths:
      - infrastructure/network/**

env:
  STACK: infrastructure/network
  AWS_ROLE_ARN: arn:aws:iam::352505431850:role/GitHubActionsTerraformRole
  WORKSPACE_REF: ${{ github.ref }}
  PLAN_CACHE_KEY: tfplan-cache-${{ github.run_id }}.${{ github.run_attempt }}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.ref_name	!= 'main'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: seanchristians/lab/actions/tailscale-login@main
        with:
          client-id: TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL
          audience: api.tailscale.com/TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL

      - name: terraform init
        uses: seanchristians/lab/actions/terraform-init@main
        with:
          stack-path: ${{ env.STACK }}
          aws-role-arn: ${{ env.AWS_ROLE_ARN }}

      - name: terraform validate
        run: |
          terraform -chdir="$STACK" validate

      - name: Configure branch workspace
        run: |
          terraform -chdir="$STACK" state pull
          terraform -chdir="$STACK" workspace new -state=terraform.tfstate "$WORKSPACE_REF"

      - name: terraform plan
        run: |
          CHANGE_CODE=0
          terraform -chdir="$STACK" plan -detailed-exitcode -compact-warnings -no-color -out=plan.tfplan || CHANGE_CODE=$?
          if [ $CHANGE_CODE -eq 1 ]; then
            exit 1
          fi
          echo "CHANGES_PLANNED=$(test $CHANGE_CODE -eq 2 && echo 'true' || echo 'false')" >> $GITHUB_ENV

      - name: Cache Terraform Plan
        if: env.CHANGES_PLANNED == true
        id: plan-cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.STACK }}
          key: ${{ env.PLAN_CACHE_KEY }}

    outputs:
      changes-planned: ${{ env.CHANGES_PLANNED }}

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: development
    needs: terraform-plan
    if: github.ref_name	!= 'main' && needs.terraform-plan.outputs.changes-planned == true
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Restore Terraform Plan
        uses: actions/cache/restore@v4
        with:
          key: ${{ env.PLAN_CACHE_KEY }}
          fail-on-cache-miss: true

      - uses: seanchristians/lab/actions/tailscale-login@main
        with:
          client-id: TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL
          audience: api.tailscale.com/TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ca-central-1
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Switch to branch workspace
        if: github.ref_name != 'main'
        run: |
          terraform -chdir="$STACK" workspace select "$WORKSPACE_REF"

      - name: terraform apply
        run: |
          terraform -chdir="$STACK" apply -input=false plan.tfplan
