name: Terraform Plan Network Stack
on:
  workflow_dispatch:
  pull_request:
    paths:
      - infrastructure/network/**

env:
  TF_IN_AUTOMATION: true
  STACK: infrastructure/network

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Authenticate Terraform Providers
        uses: seanchristians/lab/actions/terraform-provider-auth@main
        with:
          AWS_ROLE_ARN: arn:aws:iam::352505431850:role/GitHubActionsTerraformRole
          TAILSCALE_AUDIENCE: api.tailscale.com/TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL
          TAILSCALE_CLIENT_ID: TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL

      - name: Terraform Init
        uses: seanchristians/lab/actions/terraform-init@tf-init-with-cache
        with:
          working-directory: ${{ env.STACK }}

      - name: Terraform Validate
        run: |
          terraform -chdir="$STACK" validate

      - name: Terraform Plan
        run: |
          terraform -chdir="$STACK" plan -input=false -no-color -compact-warnings >> $GITHUB_STEP_SUMMARY
