name: Terraform Network Stack (development)
on:
  workflow_dispatch:
  pull_request:
    paths:
      - infrastructure/network/**

env:
  STACK: infrastructure/network
  AWS_ROLE_ARN: arn:aws:iam::352505431850:role/GitHubActionsTerraformRole
  WORKSPACE_REF: ${{ github.ref }}

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - uses: seanchristians/lab/actions/tailscale-login@main
        with:
          client-id: TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL
          audience: api.tailscale.com/TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL

      - name: terraform init
        uses: seanchristians/lab/actions/terraform-init@main
        with:
          stack-path: ${{ env.STACK }}
          aws-role-arn: ${{ env.AWS_ROLE_ARN }}

      - name: terraform validate
        run: |
          terraform -chdir="$STACK" validate

      - name: Configure branch workspace
        if: github.ref_name != 'main'
        run: |
          terraform state pull
          terraform workspace new -state=terraform.tfstate "$WORKSPACE_REF"

      - name: terraform plan
        run: |
          CHANGE_CODE=0
          terraform -chdir="$STACK" plan -detailed-exitcode -compact-warnings -no-color -out=plan.tfplan || CHANGE_CODE=$?
          if [ $CHANGE_CODE -eq 1 ]; then
            exit 1
          fi
          echo "CHANGES_PLANNED=$(test $CHANGE_CODE -eq 2 && echo 'true' || echo 'false')" >> $GITHUB_ENV

      - name: Store Plan Artifact
        if: ${{ env.CHANGES_PLANNED == true }}
        id: plan-upload-artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ github.run_id }}-terraform-plan
          path: ${{ env.STACK }}/plan.tfplan
          retention-days: 10
          overwrite: true

    outputs:
      changes-planned: ${{ env.CHANGES_PLANNED }}
      plan-artifact-name: ${{ github.run_id }}-terraform-plan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: development
    needs: terraform-plan
    if: ${{ needs.terraform-plan.outputs.changes-planned == true }}
    steps:
      - uses: seanchristians/lab/actions/tailscale-login@main
        with:
          client-id: TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL
          audience: api.tailscale.com/TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL

      - name: terraform init
        uses: seanchristians/lab/actions/terraform-init@main
        with:
          stack-path: ${{ env.STACK }}
          aws-role-arn: ${{ env.AWS_ROLE_ARN }}

      - name: Switch to branch workspace
        if: github.ref_name != 'main'
        run: |
          terraform workspace select "$WORKSPACE_REF"

      - name: Download Plan Artifact
        id: plan-download-artifact
        uses: actions/download-artifact@v6
        with:
          name: ${{ needs.terraform-plan.outputs.plan-artifact-name }}

      - name: terraform apply
        env:
          PLAN_ARTIFACT: ${{ steps.plan-download-artifact.outputs.download-path }}/plan.tfplan
        run: |
          terraform -chdir="$STACK" apply -input=false "$PLAN_ARTIFACT"
