name: stacks/network terraform plan
on:
  pull_request:
    types: [opened]
    branches: [main]
    paths:
      - infrastructure/network/**

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash
    working-directory: infrastructure/network

env:
  TAILSCALE_TAILNET: TA1163u8TV11CNTRL
  TAILSCALE_AUDIENCE: api.tailscale.com/TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub OIDC token for Tailscale
        shell: bash
        run: |
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$TAILSCALE_AUDIENCE")
          echo "TAILSCALE_IDENTITY_TOKEN=${TOKEN}" >> $GITHUB_ENV

      - name: terraform init
        uses: seanchristians/lab/infrastructure/backends/s3@main
        with:
          aws-role-arn: ${{ vars.AWS_ROLE_ARN }}

      - name: terraform plan
        run: terraform plan
