name: stacks/network terraform plan
on:
  workflow_dispatch:
  pull_request:
    paths:
      - infrastructure/network/**

env:
  stack: infrastructure/network

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash
    working-directory: ${{ env.stack }}

jobs:
  terraform-env:
    name: Terraform Backend Environment Vars
    runs-on: ubuntu-latest
    environment: terraform
    outputs:
      aws-role-arn: ${{ vars.AWS_ROLE_ARN }}

  terraform-plan:
    name: Prepare Terraform Plan
    runs-on: ubuntu-latest
    environment: development
    needs: terraform-env
    steps:
      - name: Tailscale login
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL
          audience: api.tailscale.com/TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL
          tags: tag:infrastructure

      - name: terraform init
        uses: seanchristians/lab/infrastructure/backends/s3@main
        with:
          stack-path: ${{ env.stack }}
          aws-role-arn: ${{ needs.terraform-env.outputs.aws-role-arn }}

      - name: terraform plan
        run: |
          cd '${{ env.stack }}'
          terraform plan -input=false -out=plan.tfplan

      - name: Store Plan Artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ github.ref }}-terraform-plan
          path: plan.tfplan
          retention-days: 10
          overwrite: true

  terraform-apply:
    runs-on: ubuntu-latest
    environment: production
    needs: terraform-env
