name: Terraform
on:
  workflow_dispatch:
    inputs:
      stack:
        description: Terraform Stack
        required: true
        type: choice
        options:
          - infrastructure/acme
          - infrastructure/network
  pull_request:
    paths:
      - infrastructure/**
  push:
    branches:
      - main
    paths:
      - infrastructure/**

env:
  TF_IN_AUTOMATION: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  scan-branches:
    name: Scan Stacks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ github.event_name == 'workflow_dispatch' && steps.selected-stack.outputs.stack || steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v5
      - id: changed-files
        if: github.event_name != 'workflow_dispatch'
        uses: tj-actions/changed-files@v47
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 2
          files: infrastructure/**
          files_ignore: infrastructure/backend/**
          matrix: true
      - id: selected-stack
        if: github.event_name == 'workflow_dispatch'
        env:
          STACK: ${{ inputs.stack }}
        run: |
          echo "stack=[\"$STACK\"]" >> $GITHUB_OUTPUT

  terraform-plan:
    if: github.ref_name != 'main'
    needs: scan-branches
    strategy:
      matrix:
        stack: ${{ fromJSON(needs.scan-branches.outputs.matrix) }}
      fail-fast: false
    name: Plan ${{ matrix.stack }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Authenticate Terraform Providers
        uses: ./actions/terraform-provider-auth
        with:
          stack: ${{ matrix.stack }}

      - name: Terraform Init
        uses: seanchristians/lab/actions/terraform-init@main
        with:
          working-directory: ${{ matrix.stack }}

      - name: Terraform Validate
        env:
          STACK: ${{ matrix.stack }}
        run: |
          terraform -chdir="$STACK" validate

      - name: Terraform Plan
        env:
          STACK: ${{ matrix.stack }}
        run: |
          terraform -chdir="$STACK" plan -input=false -no-color -compact-warnings >> $GITHUB_STEP_SUMMARY

  terraform-apply:
    if: github.ref_name == 'main'
    needs: scan-branches
    strategy:
      matrix:
        stack: ${{ fromJSON(needs.scan-branches.outputs.matrix) }}
      fail-fast: false
    name: Apply ${{ matrix.stack }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Authenticate Terraform Providers
        uses: ./actions/terraform-provider-auth
        with:
          stack: ${{ matrix.stack }}

      - name: Terraform Init
        uses: seanchristians/lab/actions/terraform-init@main
        with:
          working-directory: ${{ matrix.stack }}

      - name: Terraform Apply
        env:
          STACK: ${{ matrix.stack }}
        run: |
          terraform -chdir="$STACK" apply -input=false -auto-approve
